### ISSUE TITLE
Generation of a C header with I/O addresses

### ISSUE THREAD

**Issue by lawrie** [SpinalHDL/SaxonSoc#2]
The memory bus addresses and offsets used by each peripheral are part of the definition of SaxonSoc or a CustomSoc, but are also needed in the C programs that drive those peripherals. It would be useful if a C header file containing those addresses and offsets could be generated.

**Comment by Dolu1990** [comment]
For this one, we first need be sure the if we have to try to have an Vivado/QSys like interconnect system, which can eat everything. Or if we should be more restricting, and having the user to for instance instanciate various bridges as for instance BmbToApb3

@typingArtist

**Comment by lawrie** [comment]
The more restricted system with just the Bmb and Apb3 buses is fine for my purposes.

**Comment by Dolu1990** [comment]
done
