### ISSUE TITLE
SVD register descriptions

### ISSUE THREAD

**Issue by vmedea** [SpinalHDL/SaxonSoc#52]
This was mentioned on the ulx3s discord by thorns514 and I thought it was a good idea. For bare-metal programming in rust and potentially other languages, it would be useful if there were machine-parseable register descriptions in SVD format.

I'm not sure to how what point these could be automatically generated dynamically. But a start could be the Linux dts which provides the peripherals base offsets and interrupt numbers.

**Comment by mithro** [comment]
FYI - LiteX generates both SVD and Linux DeviceTree for it's SoCs.
